package Bank;

public enum localCharities {

    JUNIOR_LEAGUE_OF_WILMINGTON,
    SUNDAY_BREAKFAST_MISSION,
    MARTHA_HOUSE,
    BAYARD_HOUSE,
    LITERACY_LITERACY,
    GREEN_DROP,
    KIND_TO_KIDS,
    CONNECTIONS_COMMUNITY_SUPPORT_PROGRAM,
}
